-- Auto-generated by scripts/gen-balance-tests.ts from tests/fixtures/balance-vectors.json
-- Do not edit manually. Run 'node --experimental-strip-types scripts/gen-balance-tests.ts' to regenerate.

begin;
select plan(60);

set local role postgres;

-- Insert shared test users
insert into auth.users (id, email)
values
  ('aaaaaaaa-1111-0000-0000-000000000001', 'veca@example.com'),
  ('bbbbbbbb-2222-0000-0000-000000000002', 'vecb@example.com'),
  ('cccccccc-3333-0000-0000-000000000003', 'vecc@example.com'),
  ('dddddddd-4444-0000-0000-000000000004', 'vecd@example.com')
on conflict (id) do nothing;

-- =============================================================================
-- Vector 1: a paid ₹300, equal among a, b, c
-- =============================================================================
insert into public.groups (id, name, currency, created_by)
values ('ffffffff-0000-0000-0000-000000000001', 'Vector 1 Group', 'INR', 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.group_members (group_id, user_id, role, status)
values
  ('ffffffff-0000-0000-0000-000000000001', 'aaaaaaaa-1111-0000-0000-000000000001', 'member', 'active'),
  ('ffffffff-0000-0000-0000-000000000001', 'bbbbbbbb-2222-0000-0000-000000000002', 'member', 'active'),
  ('ffffffff-0000-0000-0000-000000000001', 'cccccccc-3333-0000-0000-000000000003', 'member', 'active');

insert into public.expenses (id, group_id, amount_minor, paid_by, split_type, expense_date, created_by)
values ('e0000000-0000-0000-0000-000000000001', 'ffffffff-0000-0000-0000-000000000001', 30000, 'aaaaaaaa-1111-0000-0000-000000000001', 'equal', current_date, 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.expense_splits (expense_id, user_id, share_minor)
values
  ('e0000000-0000-0000-0000-000000000001', 'aaaaaaaa-1111-0000-0000-000000000001', 10000),
  ('e0000000-0000-0000-0000-000000000001', 'bbbbbbbb-2222-0000-0000-000000000002', 10000),
  ('e0000000-0000-0000-0000-000000000001', 'cccccccc-3333-0000-0000-000000000003', 10000);

-- Test 1: compute_group_nets matches expected nets
select results_eq(
  $$ select member_id, net_minor from public.compute_group_nets('ffffffff-0000-0000-0000-000000000001') order by net_minor desc, member_id asc $$,
  $$ values
    ('aaaaaaaa-1111-0000-0000-000000000001'::uuid, 20000::bigint),
    ('bbbbbbbb-2222-0000-0000-000000000002'::uuid, -10000::bigint),
    ('cccccccc-3333-0000-0000-000000000003'::uuid, -10000::bigint) $$,
  'Vector 1: compute_group_nets returns exact expected nets'
);

-- Test 2: Invariant BC1: sum of all nets must be exactly 0
select is(
  (select coalesce(sum(net_minor), 0)::bigint from public.compute_group_nets('ffffffff-0000-0000-0000-000000000001')),
  0::bigint,
  'Vector 1: sum of all nets is exactly 0 (BC1)'
);

-- Test 3: compute_simplified_debts matches expected payments
select results_eq(
  $$ select seq, from_user, to_user, amount_minor from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000001') order by seq $$,
  $$ values
    (1::int, 'bbbbbbbb-2222-0000-0000-000000000002'::uuid, 'aaaaaaaa-1111-0000-0000-000000000001'::uuid, 10000::bigint),
    (2::int, 'cccccccc-3333-0000-0000-000000000003'::uuid, 'aaaaaaaa-1111-0000-0000-000000000001'::uuid, 10000::bigint) $$,
  'Vector 1: compute_simplified_debts returns exact expected suggested payments'
);

-- Test 4: Invariant BS2: applying all suggested payments brings every balance to exactly 0
with applied as (
  select n.member_id,
         (n.net_minor + coalesce(se.amt, 0) - coalesce(re.amt, 0))::bigint as final_net
    from public.compute_group_nets('ffffffff-0000-0000-0000-000000000001') n
    left join (select from_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000001') group by from_user) se on se.from_user = n.member_id
    left join (select to_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000001') group by to_user) re on re.to_user = n.member_id
)
select is(
  (select count(*)::int from applied where final_net <> 0),
  0,
  'Vector 1: applying suggested payments brings every balance to 0 (BS2)'
);

-- Test 5: Invariant BS1: at most n - 1 payments for n people with non-zero balances
select ok(
  (select count(*)::int from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000001')) <= 2,
  'Vector 1: suggested payments count <= 2 (BS1)'
);

-- =============================================================================
-- Vector 2: a paid ₹100 (10000 paise), equal among a, b, c
-- =============================================================================
insert into public.groups (id, name, currency, created_by)
values ('ffffffff-0000-0000-0000-000000000002', 'Vector 2 Group', 'INR', 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.group_members (group_id, user_id, role, status)
values
  ('ffffffff-0000-0000-0000-000000000002', 'aaaaaaaa-1111-0000-0000-000000000001', 'member', 'active'),
  ('ffffffff-0000-0000-0000-000000000002', 'bbbbbbbb-2222-0000-0000-000000000002', 'member', 'active'),
  ('ffffffff-0000-0000-0000-000000000002', 'cccccccc-3333-0000-0000-000000000003', 'member', 'active');

insert into public.expenses (id, group_id, amount_minor, paid_by, split_type, expense_date, created_by)
values ('e0000000-0000-0000-0000-000000000002', 'ffffffff-0000-0000-0000-000000000002', 10000, 'aaaaaaaa-1111-0000-0000-000000000001', 'equal', current_date, 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.expense_splits (expense_id, user_id, share_minor)
values
  ('e0000000-0000-0000-0000-000000000002', 'aaaaaaaa-1111-0000-0000-000000000001', 3334),
  ('e0000000-0000-0000-0000-000000000002', 'bbbbbbbb-2222-0000-0000-000000000002', 3333),
  ('e0000000-0000-0000-0000-000000000002', 'cccccccc-3333-0000-0000-000000000003', 3333);

-- Test 1: compute_group_nets matches expected nets
select results_eq(
  $$ select member_id, net_minor from public.compute_group_nets('ffffffff-0000-0000-0000-000000000002') order by net_minor desc, member_id asc $$,
  $$ values
    ('aaaaaaaa-1111-0000-0000-000000000001'::uuid, 6666::bigint),
    ('bbbbbbbb-2222-0000-0000-000000000002'::uuid, -3333::bigint),
    ('cccccccc-3333-0000-0000-000000000003'::uuid, -3333::bigint) $$,
  'Vector 2: compute_group_nets returns exact expected nets'
);

-- Test 2: Invariant BC1: sum of all nets must be exactly 0
select is(
  (select coalesce(sum(net_minor), 0)::bigint from public.compute_group_nets('ffffffff-0000-0000-0000-000000000002')),
  0::bigint,
  'Vector 2: sum of all nets is exactly 0 (BC1)'
);

-- Test 3: compute_simplified_debts matches expected payments
select results_eq(
  $$ select seq, from_user, to_user, amount_minor from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000002') order by seq $$,
  $$ values
    (1::int, 'bbbbbbbb-2222-0000-0000-000000000002'::uuid, 'aaaaaaaa-1111-0000-0000-000000000001'::uuid, 3333::bigint),
    (2::int, 'cccccccc-3333-0000-0000-000000000003'::uuid, 'aaaaaaaa-1111-0000-0000-000000000001'::uuid, 3333::bigint) $$,
  'Vector 2: compute_simplified_debts returns exact expected suggested payments'
);

-- Test 4: Invariant BS2: applying all suggested payments brings every balance to exactly 0
with applied as (
  select n.member_id,
         (n.net_minor + coalesce(se.amt, 0) - coalesce(re.amt, 0))::bigint as final_net
    from public.compute_group_nets('ffffffff-0000-0000-0000-000000000002') n
    left join (select from_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000002') group by from_user) se on se.from_user = n.member_id
    left join (select to_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000002') group by to_user) re on re.to_user = n.member_id
)
select is(
  (select count(*)::int from applied where final_net <> 0),
  0,
  'Vector 2: applying suggested payments brings every balance to 0 (BS2)'
);

-- Test 5: Invariant BS1: at most n - 1 payments for n people with non-zero balances
select ok(
  (select count(*)::int from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000002')) <= 2,
  'Vector 2: suggested payments count <= 2 (BS1)'
);

-- =============================================================================
-- Vector 3: a paid ₹300 for a, b (150 each); b paid ₹300 for a, b (150 each)
-- =============================================================================
insert into public.groups (id, name, currency, created_by)
values ('ffffffff-0000-0000-0000-000000000003', 'Vector 3 Group', 'INR', 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.group_members (group_id, user_id, role, status)
values
  ('ffffffff-0000-0000-0000-000000000003', 'aaaaaaaa-1111-0000-0000-000000000001', 'member', 'active'),
  ('ffffffff-0000-0000-0000-000000000003', 'bbbbbbbb-2222-0000-0000-000000000002', 'member', 'active'),
  ('ffffffff-0000-0000-0000-000000000003', 'cccccccc-3333-0000-0000-000000000003', 'member', 'active');

insert into public.expenses (id, group_id, amount_minor, paid_by, split_type, expense_date, created_by)
values ('e0000000-0000-0000-0000-000000000003', 'ffffffff-0000-0000-0000-000000000003', 30000, 'aaaaaaaa-1111-0000-0000-000000000001', 'equal', current_date, 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.expense_splits (expense_id, user_id, share_minor)
values
  ('e0000000-0000-0000-0000-000000000003', 'aaaaaaaa-1111-0000-0000-000000000001', 15000),
  ('e0000000-0000-0000-0000-000000000003', 'bbbbbbbb-2222-0000-0000-000000000002', 15000);

insert into public.expenses (id, group_id, amount_minor, paid_by, split_type, expense_date, created_by)
values ('e0000000-0000-0000-0000-000000000004', 'ffffffff-0000-0000-0000-000000000003', 30000, 'bbbbbbbb-2222-0000-0000-000000000002', 'equal', current_date, 'bbbbbbbb-2222-0000-0000-000000000002');

insert into public.expense_splits (expense_id, user_id, share_minor)
values
  ('e0000000-0000-0000-0000-000000000004', 'aaaaaaaa-1111-0000-0000-000000000001', 15000),
  ('e0000000-0000-0000-0000-000000000004', 'bbbbbbbb-2222-0000-0000-000000000002', 15000);

-- Test 1: compute_group_nets matches expected nets
select results_eq(
  $$ select member_id, net_minor from public.compute_group_nets('ffffffff-0000-0000-0000-000000000003') order by net_minor desc, member_id asc $$,
  $$ values
    ('aaaaaaaa-1111-0000-0000-000000000001'::uuid, 0::bigint),
    ('bbbbbbbb-2222-0000-0000-000000000002'::uuid, 0::bigint),
    ('cccccccc-3333-0000-0000-000000000003'::uuid, 0::bigint) $$,
  'Vector 3: compute_group_nets returns exact expected nets'
);

-- Test 2: Invariant BC1: sum of all nets must be exactly 0
select is(
  (select coalesce(sum(net_minor), 0)::bigint from public.compute_group_nets('ffffffff-0000-0000-0000-000000000003')),
  0::bigint,
  'Vector 3: sum of all nets is exactly 0 (BC1)'
);

-- Test 3: compute_simplified_debts matches expected payments
select is_empty(
  $$ select seq, from_user, to_user, amount_minor from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000003') $$,
  'Vector 3: compute_simplified_debts returns empty when all settled'
);

-- Test 4: Invariant BS2: applying all suggested payments brings every balance to exactly 0
with applied as (
  select n.member_id,
         (n.net_minor + coalesce(se.amt, 0) - coalesce(re.amt, 0))::bigint as final_net
    from public.compute_group_nets('ffffffff-0000-0000-0000-000000000003') n
    left join (select from_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000003') group by from_user) se on se.from_user = n.member_id
    left join (select to_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000003') group by to_user) re on re.to_user = n.member_id
)
select is(
  (select count(*)::int from applied where final_net <> 0),
  0,
  'Vector 3: applying suggested payments brings every balance to 0 (BS2)'
);

-- Test 5: Invariant BS1: at most n - 1 payments for n people with non-zero balances
select ok(
  (select count(*)::int from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000003')) <= 0,
  'Vector 3: suggested payments count <= 0 (BS1)'
);

-- =============================================================================
-- Vector 4: a paid ₹200 for b only; b paid ₹200 for c only
-- =============================================================================
insert into public.groups (id, name, currency, created_by)
values ('ffffffff-0000-0000-0000-000000000004', 'Vector 4 Group', 'INR', 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.group_members (group_id, user_id, role, status)
values
  ('ffffffff-0000-0000-0000-000000000004', 'aaaaaaaa-1111-0000-0000-000000000001', 'member', 'active'),
  ('ffffffff-0000-0000-0000-000000000004', 'bbbbbbbb-2222-0000-0000-000000000002', 'member', 'active'),
  ('ffffffff-0000-0000-0000-000000000004', 'cccccccc-3333-0000-0000-000000000003', 'member', 'active');

insert into public.expenses (id, group_id, amount_minor, paid_by, split_type, expense_date, created_by)
values ('e0000000-0000-0000-0000-000000000005', 'ffffffff-0000-0000-0000-000000000004', 20000, 'aaaaaaaa-1111-0000-0000-000000000001', 'exact', current_date, 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.expense_splits (expense_id, user_id, share_minor)
values
  ('e0000000-0000-0000-0000-000000000005', 'bbbbbbbb-2222-0000-0000-000000000002', 20000);

insert into public.expenses (id, group_id, amount_minor, paid_by, split_type, expense_date, created_by)
values ('e0000000-0000-0000-0000-000000000006', 'ffffffff-0000-0000-0000-000000000004', 20000, 'bbbbbbbb-2222-0000-0000-000000000002', 'exact', current_date, 'bbbbbbbb-2222-0000-0000-000000000002');

insert into public.expense_splits (expense_id, user_id, share_minor)
values
  ('e0000000-0000-0000-0000-000000000006', 'cccccccc-3333-0000-0000-000000000003', 20000);

-- Test 1: compute_group_nets matches expected nets
select results_eq(
  $$ select member_id, net_minor from public.compute_group_nets('ffffffff-0000-0000-0000-000000000004') order by net_minor desc, member_id asc $$,
  $$ values
    ('aaaaaaaa-1111-0000-0000-000000000001'::uuid, 20000::bigint),
    ('bbbbbbbb-2222-0000-0000-000000000002'::uuid, 0::bigint),
    ('cccccccc-3333-0000-0000-000000000003'::uuid, -20000::bigint) $$,
  'Vector 4: compute_group_nets returns exact expected nets'
);

-- Test 2: Invariant BC1: sum of all nets must be exactly 0
select is(
  (select coalesce(sum(net_minor), 0)::bigint from public.compute_group_nets('ffffffff-0000-0000-0000-000000000004')),
  0::bigint,
  'Vector 4: sum of all nets is exactly 0 (BC1)'
);

-- Test 3: compute_simplified_debts matches expected payments
select results_eq(
  $$ select seq, from_user, to_user, amount_minor from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000004') order by seq $$,
  $$ values
    (1::int, 'cccccccc-3333-0000-0000-000000000003'::uuid, 'aaaaaaaa-1111-0000-0000-000000000001'::uuid, 20000::bigint) $$,
  'Vector 4: compute_simplified_debts returns exact expected suggested payments'
);

-- Test 4: Invariant BS2: applying all suggested payments brings every balance to exactly 0
with applied as (
  select n.member_id,
         (n.net_minor + coalesce(se.amt, 0) - coalesce(re.amt, 0))::bigint as final_net
    from public.compute_group_nets('ffffffff-0000-0000-0000-000000000004') n
    left join (select from_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000004') group by from_user) se on se.from_user = n.member_id
    left join (select to_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000004') group by to_user) re on re.to_user = n.member_id
)
select is(
  (select count(*)::int from applied where final_net <> 0),
  0,
  'Vector 4: applying suggested payments brings every balance to 0 (BS2)'
);

-- Test 5: Invariant BS1: at most n - 1 payments for n people with non-zero balances
select ok(
  (select count(*)::int from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000004')) <= 1,
  'Vector 4: suggested payments count <= 1 (BS1)'
);

-- =============================================================================
-- Vector 5: Vector 1, then confirmed payment b→a ₹100
-- =============================================================================
insert into public.groups (id, name, currency, created_by)
values ('ffffffff-0000-0000-0000-000000000005', 'Vector 5 Group', 'INR', 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.group_members (group_id, user_id, role, status)
values
  ('ffffffff-0000-0000-0000-000000000005', 'aaaaaaaa-1111-0000-0000-000000000001', 'member', 'active'),
  ('ffffffff-0000-0000-0000-000000000005', 'bbbbbbbb-2222-0000-0000-000000000002', 'member', 'active'),
  ('ffffffff-0000-0000-0000-000000000005', 'cccccccc-3333-0000-0000-000000000003', 'member', 'active');

insert into public.expenses (id, group_id, amount_minor, paid_by, split_type, expense_date, created_by)
values ('e0000000-0000-0000-0000-000000000007', 'ffffffff-0000-0000-0000-000000000005', 30000, 'aaaaaaaa-1111-0000-0000-000000000001', 'equal', current_date, 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.expense_splits (expense_id, user_id, share_minor)
values
  ('e0000000-0000-0000-0000-000000000007', 'aaaaaaaa-1111-0000-0000-000000000001', 10000),
  ('e0000000-0000-0000-0000-000000000007', 'bbbbbbbb-2222-0000-0000-000000000002', 10000),
  ('e0000000-0000-0000-0000-000000000007', 'cccccccc-3333-0000-0000-000000000003', 10000);

insert into public.settlements (id, group_id, from_user, to_user, amount_minor, method, status, created_by, confirmed_at)
values ('50000000-0000-0000-0000-000000000001', 'ffffffff-0000-0000-0000-000000000005', 'bbbbbbbb-2222-0000-0000-000000000002', 'aaaaaaaa-1111-0000-0000-000000000001', 10000, 'cash', 'confirmed', 'bbbbbbbb-2222-0000-0000-000000000002', now());

-- Test 1: compute_group_nets matches expected nets
select results_eq(
  $$ select member_id, net_minor from public.compute_group_nets('ffffffff-0000-0000-0000-000000000005') order by net_minor desc, member_id asc $$,
  $$ values
    ('aaaaaaaa-1111-0000-0000-000000000001'::uuid, 10000::bigint),
    ('bbbbbbbb-2222-0000-0000-000000000002'::uuid, 0::bigint),
    ('cccccccc-3333-0000-0000-000000000003'::uuid, -10000::bigint) $$,
  'Vector 5: compute_group_nets returns exact expected nets'
);

-- Test 2: Invariant BC1: sum of all nets must be exactly 0
select is(
  (select coalesce(sum(net_minor), 0)::bigint from public.compute_group_nets('ffffffff-0000-0000-0000-000000000005')),
  0::bigint,
  'Vector 5: sum of all nets is exactly 0 (BC1)'
);

-- Test 3: compute_simplified_debts matches expected payments
select results_eq(
  $$ select seq, from_user, to_user, amount_minor from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000005') order by seq $$,
  $$ values
    (1::int, 'cccccccc-3333-0000-0000-000000000003'::uuid, 'aaaaaaaa-1111-0000-0000-000000000001'::uuid, 10000::bigint) $$,
  'Vector 5: compute_simplified_debts returns exact expected suggested payments'
);

-- Test 4: Invariant BS2: applying all suggested payments brings every balance to exactly 0
with applied as (
  select n.member_id,
         (n.net_minor + coalesce(se.amt, 0) - coalesce(re.amt, 0))::bigint as final_net
    from public.compute_group_nets('ffffffff-0000-0000-0000-000000000005') n
    left join (select from_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000005') group by from_user) se on se.from_user = n.member_id
    left join (select to_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000005') group by to_user) re on re.to_user = n.member_id
)
select is(
  (select count(*)::int from applied where final_net <> 0),
  0,
  'Vector 5: applying suggested payments brings every balance to 0 (BS2)'
);

-- Test 5: Invariant BS1: at most n - 1 payments for n people with non-zero balances
select ok(
  (select count(*)::int from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000005')) <= 1,
  'Vector 5: suggested payments count <= 1 (BS1)'
);

-- =============================================================================
-- Vector 6: Vector 1 plus a pending payment b→a ₹100
-- =============================================================================
insert into public.groups (id, name, currency, created_by)
values ('ffffffff-0000-0000-0000-000000000006', 'Vector 6 Group', 'INR', 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.group_members (group_id, user_id, role, status)
values
  ('ffffffff-0000-0000-0000-000000000006', 'aaaaaaaa-1111-0000-0000-000000000001', 'member', 'active'),
  ('ffffffff-0000-0000-0000-000000000006', 'bbbbbbbb-2222-0000-0000-000000000002', 'member', 'active'),
  ('ffffffff-0000-0000-0000-000000000006', 'cccccccc-3333-0000-0000-000000000003', 'member', 'active');

insert into public.expenses (id, group_id, amount_minor, paid_by, split_type, expense_date, created_by)
values ('e0000000-0000-0000-0000-000000000008', 'ffffffff-0000-0000-0000-000000000006', 30000, 'aaaaaaaa-1111-0000-0000-000000000001', 'equal', current_date, 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.expense_splits (expense_id, user_id, share_minor)
values
  ('e0000000-0000-0000-0000-000000000008', 'aaaaaaaa-1111-0000-0000-000000000001', 10000),
  ('e0000000-0000-0000-0000-000000000008', 'bbbbbbbb-2222-0000-0000-000000000002', 10000),
  ('e0000000-0000-0000-0000-000000000008', 'cccccccc-3333-0000-0000-000000000003', 10000);

insert into public.settlements (id, group_id, from_user, to_user, amount_minor, method, status, created_by)
values ('50000000-0000-0000-0000-000000000002', 'ffffffff-0000-0000-0000-000000000006', 'bbbbbbbb-2222-0000-0000-000000000002', 'aaaaaaaa-1111-0000-0000-000000000001', 10000, 'cash', 'pending', 'bbbbbbbb-2222-0000-0000-000000000002');

-- Test 1: compute_group_nets matches expected nets
select results_eq(
  $$ select member_id, net_minor from public.compute_group_nets('ffffffff-0000-0000-0000-000000000006') order by net_minor desc, member_id asc $$,
  $$ values
    ('aaaaaaaa-1111-0000-0000-000000000001'::uuid, 20000::bigint),
    ('bbbbbbbb-2222-0000-0000-000000000002'::uuid, -10000::bigint),
    ('cccccccc-3333-0000-0000-000000000003'::uuid, -10000::bigint) $$,
  'Vector 6: compute_group_nets returns exact expected nets'
);

-- Test 2: Invariant BC1: sum of all nets must be exactly 0
select is(
  (select coalesce(sum(net_minor), 0)::bigint from public.compute_group_nets('ffffffff-0000-0000-0000-000000000006')),
  0::bigint,
  'Vector 6: sum of all nets is exactly 0 (BC1)'
);

-- Test 3: compute_simplified_debts matches expected payments
select results_eq(
  $$ select seq, from_user, to_user, amount_minor from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000006') order by seq $$,
  $$ values
    (1::int, 'bbbbbbbb-2222-0000-0000-000000000002'::uuid, 'aaaaaaaa-1111-0000-0000-000000000001'::uuid, 10000::bigint),
    (2::int, 'cccccccc-3333-0000-0000-000000000003'::uuid, 'aaaaaaaa-1111-0000-0000-000000000001'::uuid, 10000::bigint) $$,
  'Vector 6: compute_simplified_debts returns exact expected suggested payments'
);

-- Test 4: Invariant BS2: applying all suggested payments brings every balance to exactly 0
with applied as (
  select n.member_id,
         (n.net_minor + coalesce(se.amt, 0) - coalesce(re.amt, 0))::bigint as final_net
    from public.compute_group_nets('ffffffff-0000-0000-0000-000000000006') n
    left join (select from_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000006') group by from_user) se on se.from_user = n.member_id
    left join (select to_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000006') group by to_user) re on re.to_user = n.member_id
)
select is(
  (select count(*)::int from applied where final_net <> 0),
  0,
  'Vector 6: applying suggested payments brings every balance to 0 (BS2)'
);

-- Test 5: Invariant BS1: at most n - 1 payments for n people with non-zero balances
select ok(
  (select count(*)::int from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000006')) <= 2,
  'Vector 6: suggested payments count <= 2 (BS1)'
);

-- =============================================================================
-- Vector 7: Vector 1 plus a disputed and a cancelled payment
-- =============================================================================
insert into public.groups (id, name, currency, created_by)
values ('ffffffff-0000-0000-0000-000000000007', 'Vector 7 Group', 'INR', 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.group_members (group_id, user_id, role, status)
values
  ('ffffffff-0000-0000-0000-000000000007', 'aaaaaaaa-1111-0000-0000-000000000001', 'member', 'active'),
  ('ffffffff-0000-0000-0000-000000000007', 'bbbbbbbb-2222-0000-0000-000000000002', 'member', 'active'),
  ('ffffffff-0000-0000-0000-000000000007', 'cccccccc-3333-0000-0000-000000000003', 'member', 'active');

insert into public.expenses (id, group_id, amount_minor, paid_by, split_type, expense_date, created_by)
values ('e0000000-0000-0000-0000-000000000009', 'ffffffff-0000-0000-0000-000000000007', 30000, 'aaaaaaaa-1111-0000-0000-000000000001', 'equal', current_date, 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.expense_splits (expense_id, user_id, share_minor)
values
  ('e0000000-0000-0000-0000-000000000009', 'aaaaaaaa-1111-0000-0000-000000000001', 10000),
  ('e0000000-0000-0000-0000-000000000009', 'bbbbbbbb-2222-0000-0000-000000000002', 10000),
  ('e0000000-0000-0000-0000-000000000009', 'cccccccc-3333-0000-0000-000000000003', 10000);

insert into public.settlements (id, group_id, from_user, to_user, amount_minor, method, status, created_by)
values ('50000000-0000-0000-0000-000000000003', 'ffffffff-0000-0000-0000-000000000007', 'bbbbbbbb-2222-0000-0000-000000000002', 'aaaaaaaa-1111-0000-0000-000000000001', 5000, 'cash', 'disputed', 'bbbbbbbb-2222-0000-0000-000000000002');

insert into public.settlements (id, group_id, from_user, to_user, amount_minor, method, status, created_by)
values ('50000000-0000-0000-0000-000000000004', 'ffffffff-0000-0000-0000-000000000007', 'cccccccc-3333-0000-0000-000000000003', 'aaaaaaaa-1111-0000-0000-000000000001', 5000, 'cash', 'cancelled', 'cccccccc-3333-0000-0000-000000000003');

-- Test 1: compute_group_nets matches expected nets
select results_eq(
  $$ select member_id, net_minor from public.compute_group_nets('ffffffff-0000-0000-0000-000000000007') order by net_minor desc, member_id asc $$,
  $$ values
    ('aaaaaaaa-1111-0000-0000-000000000001'::uuid, 20000::bigint),
    ('bbbbbbbb-2222-0000-0000-000000000002'::uuid, -10000::bigint),
    ('cccccccc-3333-0000-0000-000000000003'::uuid, -10000::bigint) $$,
  'Vector 7: compute_group_nets returns exact expected nets'
);

-- Test 2: Invariant BC1: sum of all nets must be exactly 0
select is(
  (select coalesce(sum(net_minor), 0)::bigint from public.compute_group_nets('ffffffff-0000-0000-0000-000000000007')),
  0::bigint,
  'Vector 7: sum of all nets is exactly 0 (BC1)'
);

-- Test 3: compute_simplified_debts matches expected payments
select results_eq(
  $$ select seq, from_user, to_user, amount_minor from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000007') order by seq $$,
  $$ values
    (1::int, 'bbbbbbbb-2222-0000-0000-000000000002'::uuid, 'aaaaaaaa-1111-0000-0000-000000000001'::uuid, 10000::bigint),
    (2::int, 'cccccccc-3333-0000-0000-000000000003'::uuid, 'aaaaaaaa-1111-0000-0000-000000000001'::uuid, 10000::bigint) $$,
  'Vector 7: compute_simplified_debts returns exact expected suggested payments'
);

-- Test 4: Invariant BS2: applying all suggested payments brings every balance to exactly 0
with applied as (
  select n.member_id,
         (n.net_minor + coalesce(se.amt, 0) - coalesce(re.amt, 0))::bigint as final_net
    from public.compute_group_nets('ffffffff-0000-0000-0000-000000000007') n
    left join (select from_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000007') group by from_user) se on se.from_user = n.member_id
    left join (select to_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000007') group by to_user) re on re.to_user = n.member_id
)
select is(
  (select count(*)::int from applied where final_net <> 0),
  0,
  'Vector 7: applying suggested payments brings every balance to 0 (BS2)'
);

-- Test 5: Invariant BS1: at most n - 1 payments for n people with non-zero balances
select ok(
  (select count(*)::int from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000007')) <= 2,
  'Vector 7: suggested payments count <= 2 (BS1)'
);

-- =============================================================================
-- Vector 8: Vector 1, then confirmed overpayment c→a ₹150
-- =============================================================================
insert into public.groups (id, name, currency, created_by)
values ('ffffffff-0000-0000-0000-000000000008', 'Vector 8 Group', 'INR', 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.group_members (group_id, user_id, role, status)
values
  ('ffffffff-0000-0000-0000-000000000008', 'aaaaaaaa-1111-0000-0000-000000000001', 'member', 'active'),
  ('ffffffff-0000-0000-0000-000000000008', 'bbbbbbbb-2222-0000-0000-000000000002', 'member', 'active'),
  ('ffffffff-0000-0000-0000-000000000008', 'cccccccc-3333-0000-0000-000000000003', 'member', 'active');

insert into public.expenses (id, group_id, amount_minor, paid_by, split_type, expense_date, created_by)
values ('e0000000-0000-0000-0000-000000000010', 'ffffffff-0000-0000-0000-000000000008', 30000, 'aaaaaaaa-1111-0000-0000-000000000001', 'equal', current_date, 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.expense_splits (expense_id, user_id, share_minor)
values
  ('e0000000-0000-0000-0000-000000000010', 'aaaaaaaa-1111-0000-0000-000000000001', 10000),
  ('e0000000-0000-0000-0000-000000000010', 'bbbbbbbb-2222-0000-0000-000000000002', 10000),
  ('e0000000-0000-0000-0000-000000000010', 'cccccccc-3333-0000-0000-000000000003', 10000);

insert into public.settlements (id, group_id, from_user, to_user, amount_minor, method, status, created_by, confirmed_at)
values ('50000000-0000-0000-0000-000000000005', 'ffffffff-0000-0000-0000-000000000008', 'cccccccc-3333-0000-0000-000000000003', 'aaaaaaaa-1111-0000-0000-000000000001', 15000, 'cash', 'confirmed', 'cccccccc-3333-0000-0000-000000000003', now());

-- Test 1: compute_group_nets matches expected nets
select results_eq(
  $$ select member_id, net_minor from public.compute_group_nets('ffffffff-0000-0000-0000-000000000008') order by net_minor desc, member_id asc $$,
  $$ values
    ('aaaaaaaa-1111-0000-0000-000000000001'::uuid, 5000::bigint),
    ('cccccccc-3333-0000-0000-000000000003'::uuid, 5000::bigint),
    ('bbbbbbbb-2222-0000-0000-000000000002'::uuid, -10000::bigint) $$,
  'Vector 8: compute_group_nets returns exact expected nets'
);

-- Test 2: Invariant BC1: sum of all nets must be exactly 0
select is(
  (select coalesce(sum(net_minor), 0)::bigint from public.compute_group_nets('ffffffff-0000-0000-0000-000000000008')),
  0::bigint,
  'Vector 8: sum of all nets is exactly 0 (BC1)'
);

-- Test 3: compute_simplified_debts matches expected payments
select results_eq(
  $$ select seq, from_user, to_user, amount_minor from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000008') order by seq $$,
  $$ values
    (1::int, 'bbbbbbbb-2222-0000-0000-000000000002'::uuid, 'aaaaaaaa-1111-0000-0000-000000000001'::uuid, 5000::bigint),
    (2::int, 'bbbbbbbb-2222-0000-0000-000000000002'::uuid, 'cccccccc-3333-0000-0000-000000000003'::uuid, 5000::bigint) $$,
  'Vector 8: compute_simplified_debts returns exact expected suggested payments'
);

-- Test 4: Invariant BS2: applying all suggested payments brings every balance to exactly 0
with applied as (
  select n.member_id,
         (n.net_minor + coalesce(se.amt, 0) - coalesce(re.amt, 0))::bigint as final_net
    from public.compute_group_nets('ffffffff-0000-0000-0000-000000000008') n
    left join (select from_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000008') group by from_user) se on se.from_user = n.member_id
    left join (select to_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000008') group by to_user) re on re.to_user = n.member_id
)
select is(
  (select count(*)::int from applied where final_net <> 0),
  0,
  'Vector 8: applying suggested payments brings every balance to 0 (BS2)'
);

-- Test 5: Invariant BS1: at most n - 1 payments for n people with non-zero balances
select ok(
  (select count(*)::int from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000008')) <= 2,
  'Vector 8: suggested payments count <= 2 (BS1)'
);

-- =============================================================================
-- Vector 9: Vector 1, then the expense is soft-deleted
-- =============================================================================
insert into public.groups (id, name, currency, created_by)
values ('ffffffff-0000-0000-0000-000000000009', 'Vector 9 Group', 'INR', 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.group_members (group_id, user_id, role, status)
values
  ('ffffffff-0000-0000-0000-000000000009', 'aaaaaaaa-1111-0000-0000-000000000001', 'member', 'active'),
  ('ffffffff-0000-0000-0000-000000000009', 'bbbbbbbb-2222-0000-0000-000000000002', 'member', 'active'),
  ('ffffffff-0000-0000-0000-000000000009', 'cccccccc-3333-0000-0000-000000000003', 'member', 'active');

insert into public.expenses (id, group_id, amount_minor, paid_by, split_type, expense_date, created_by, deleted_at, deleted_by)
values ('e0000000-0000-0000-0000-000000000011', 'ffffffff-0000-0000-0000-000000000009', 30000, 'aaaaaaaa-1111-0000-0000-000000000001', 'equal', current_date, 'aaaaaaaa-1111-0000-0000-000000000001', now(), 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.expense_splits (expense_id, user_id, share_minor)
values
  ('e0000000-0000-0000-0000-000000000011', 'aaaaaaaa-1111-0000-0000-000000000001', 10000),
  ('e0000000-0000-0000-0000-000000000011', 'bbbbbbbb-2222-0000-0000-000000000002', 10000),
  ('e0000000-0000-0000-0000-000000000011', 'cccccccc-3333-0000-0000-000000000003', 10000);

-- Test 1: compute_group_nets matches expected nets
select results_eq(
  $$ select member_id, net_minor from public.compute_group_nets('ffffffff-0000-0000-0000-000000000009') order by net_minor desc, member_id asc $$,
  $$ values
    ('aaaaaaaa-1111-0000-0000-000000000001'::uuid, 0::bigint),
    ('bbbbbbbb-2222-0000-0000-000000000002'::uuid, 0::bigint),
    ('cccccccc-3333-0000-0000-000000000003'::uuid, 0::bigint) $$,
  'Vector 9: compute_group_nets returns exact expected nets'
);

-- Test 2: Invariant BC1: sum of all nets must be exactly 0
select is(
  (select coalesce(sum(net_minor), 0)::bigint from public.compute_group_nets('ffffffff-0000-0000-0000-000000000009')),
  0::bigint,
  'Vector 9: sum of all nets is exactly 0 (BC1)'
);

-- Test 3: compute_simplified_debts matches expected payments
select is_empty(
  $$ select seq, from_user, to_user, amount_minor from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000009') $$,
  'Vector 9: compute_simplified_debts returns empty when all settled'
);

-- Test 4: Invariant BS2: applying all suggested payments brings every balance to exactly 0
with applied as (
  select n.member_id,
         (n.net_minor + coalesce(se.amt, 0) - coalesce(re.amt, 0))::bigint as final_net
    from public.compute_group_nets('ffffffff-0000-0000-0000-000000000009') n
    left join (select from_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000009') group by from_user) se on se.from_user = n.member_id
    left join (select to_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000009') group by to_user) re on re.to_user = n.member_id
)
select is(
  (select count(*)::int from applied where final_net <> 0),
  0,
  'Vector 9: applying suggested payments brings every balance to 0 (BS2)'
);

-- Test 5: Invariant BS1: at most n - 1 payments for n people with non-zero balances
select ok(
  (select count(*)::int from public.compute_simplified_debts('ffffffff-0000-0000-0000-000000000009')) <= 0,
  'Vector 9: suggested payments count <= 0 (BS1)'
);

-- =============================================================================
-- Vector 10: a paid ₹400, equal among a, b, c, d
-- =============================================================================
insert into public.groups (id, name, currency, created_by)
values ('ffffffff-0000-0000-0000-00000000000a', 'Vector 10 Group', 'INR', 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.group_members (group_id, user_id, role, status)
values
  ('ffffffff-0000-0000-0000-00000000000a', 'aaaaaaaa-1111-0000-0000-000000000001', 'member', 'active'),
  ('ffffffff-0000-0000-0000-00000000000a', 'bbbbbbbb-2222-0000-0000-000000000002', 'member', 'active'),
  ('ffffffff-0000-0000-0000-00000000000a', 'cccccccc-3333-0000-0000-000000000003', 'member', 'active'),
  ('ffffffff-0000-0000-0000-00000000000a', 'dddddddd-4444-0000-0000-000000000004', 'member', 'active');

insert into public.expenses (id, group_id, amount_minor, paid_by, split_type, expense_date, created_by)
values ('e0000000-0000-0000-0000-000000000012', 'ffffffff-0000-0000-0000-00000000000a', 40000, 'aaaaaaaa-1111-0000-0000-000000000001', 'equal', current_date, 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.expense_splits (expense_id, user_id, share_minor)
values
  ('e0000000-0000-0000-0000-000000000012', 'aaaaaaaa-1111-0000-0000-000000000001', 10000),
  ('e0000000-0000-0000-0000-000000000012', 'bbbbbbbb-2222-0000-0000-000000000002', 10000),
  ('e0000000-0000-0000-0000-000000000012', 'cccccccc-3333-0000-0000-000000000003', 10000),
  ('e0000000-0000-0000-0000-000000000012', 'dddddddd-4444-0000-0000-000000000004', 10000);

-- Test 1: compute_group_nets matches expected nets
select results_eq(
  $$ select member_id, net_minor from public.compute_group_nets('ffffffff-0000-0000-0000-00000000000a') order by net_minor desc, member_id asc $$,
  $$ values
    ('aaaaaaaa-1111-0000-0000-000000000001'::uuid, 30000::bigint),
    ('bbbbbbbb-2222-0000-0000-000000000002'::uuid, -10000::bigint),
    ('cccccccc-3333-0000-0000-000000000003'::uuid, -10000::bigint),
    ('dddddddd-4444-0000-0000-000000000004'::uuid, -10000::bigint) $$,
  'Vector 10: compute_group_nets returns exact expected nets'
);

-- Test 2: Invariant BC1: sum of all nets must be exactly 0
select is(
  (select coalesce(sum(net_minor), 0)::bigint from public.compute_group_nets('ffffffff-0000-0000-0000-00000000000a')),
  0::bigint,
  'Vector 10: sum of all nets is exactly 0 (BC1)'
);

-- Test 3: compute_simplified_debts matches expected payments
select results_eq(
  $$ select seq, from_user, to_user, amount_minor from public.compute_simplified_debts('ffffffff-0000-0000-0000-00000000000a') order by seq $$,
  $$ values
    (1::int, 'bbbbbbbb-2222-0000-0000-000000000002'::uuid, 'aaaaaaaa-1111-0000-0000-000000000001'::uuid, 10000::bigint),
    (2::int, 'cccccccc-3333-0000-0000-000000000003'::uuid, 'aaaaaaaa-1111-0000-0000-000000000001'::uuid, 10000::bigint),
    (3::int, 'dddddddd-4444-0000-0000-000000000004'::uuid, 'aaaaaaaa-1111-0000-0000-000000000001'::uuid, 10000::bigint) $$,
  'Vector 10: compute_simplified_debts returns exact expected suggested payments'
);

-- Test 4: Invariant BS2: applying all suggested payments brings every balance to exactly 0
with applied as (
  select n.member_id,
         (n.net_minor + coalesce(se.amt, 0) - coalesce(re.amt, 0))::bigint as final_net
    from public.compute_group_nets('ffffffff-0000-0000-0000-00000000000a') n
    left join (select from_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-00000000000a') group by from_user) se on se.from_user = n.member_id
    left join (select to_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-00000000000a') group by to_user) re on re.to_user = n.member_id
)
select is(
  (select count(*)::int from applied where final_net <> 0),
  0,
  'Vector 10: applying suggested payments brings every balance to 0 (BS2)'
);

-- Test 5: Invariant BS1: at most n - 1 payments for n people with non-zero balances
select ok(
  (select count(*)::int from public.compute_simplified_debts('ffffffff-0000-0000-0000-00000000000a')) <= 3,
  'Vector 10: suggested payments count <= 3 (BS1)'
);

-- =============================================================================
-- Vector 11: a paid ₹600 for a, b, c (200 each); b paid ₹300 for b, c, d (100 each)
-- =============================================================================
insert into public.groups (id, name, currency, created_by)
values ('ffffffff-0000-0000-0000-00000000000b', 'Vector 11 Group', 'INR', 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.group_members (group_id, user_id, role, status)
values
  ('ffffffff-0000-0000-0000-00000000000b', 'aaaaaaaa-1111-0000-0000-000000000001', 'member', 'active'),
  ('ffffffff-0000-0000-0000-00000000000b', 'bbbbbbbb-2222-0000-0000-000000000002', 'member', 'active'),
  ('ffffffff-0000-0000-0000-00000000000b', 'cccccccc-3333-0000-0000-000000000003', 'member', 'active'),
  ('ffffffff-0000-0000-0000-00000000000b', 'dddddddd-4444-0000-0000-000000000004', 'member', 'active');

insert into public.expenses (id, group_id, amount_minor, paid_by, split_type, expense_date, created_by)
values ('e0000000-0000-0000-0000-000000000013', 'ffffffff-0000-0000-0000-00000000000b', 60000, 'aaaaaaaa-1111-0000-0000-000000000001', 'equal', current_date, 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.expense_splits (expense_id, user_id, share_minor)
values
  ('e0000000-0000-0000-0000-000000000013', 'aaaaaaaa-1111-0000-0000-000000000001', 20000),
  ('e0000000-0000-0000-0000-000000000013', 'bbbbbbbb-2222-0000-0000-000000000002', 20000),
  ('e0000000-0000-0000-0000-000000000013', 'cccccccc-3333-0000-0000-000000000003', 20000);

insert into public.expenses (id, group_id, amount_minor, paid_by, split_type, expense_date, created_by)
values ('e0000000-0000-0000-0000-000000000014', 'ffffffff-0000-0000-0000-00000000000b', 30000, 'bbbbbbbb-2222-0000-0000-000000000002', 'equal', current_date, 'bbbbbbbb-2222-0000-0000-000000000002');

insert into public.expense_splits (expense_id, user_id, share_minor)
values
  ('e0000000-0000-0000-0000-000000000014', 'bbbbbbbb-2222-0000-0000-000000000002', 10000),
  ('e0000000-0000-0000-0000-000000000014', 'cccccccc-3333-0000-0000-000000000003', 10000),
  ('e0000000-0000-0000-0000-000000000014', 'dddddddd-4444-0000-0000-000000000004', 10000);

-- Test 1: compute_group_nets matches expected nets
select results_eq(
  $$ select member_id, net_minor from public.compute_group_nets('ffffffff-0000-0000-0000-00000000000b') order by net_minor desc, member_id asc $$,
  $$ values
    ('aaaaaaaa-1111-0000-0000-000000000001'::uuid, 40000::bigint),
    ('bbbbbbbb-2222-0000-0000-000000000002'::uuid, 0::bigint),
    ('dddddddd-4444-0000-0000-000000000004'::uuid, -10000::bigint),
    ('cccccccc-3333-0000-0000-000000000003'::uuid, -30000::bigint) $$,
  'Vector 11: compute_group_nets returns exact expected nets'
);

-- Test 2: Invariant BC1: sum of all nets must be exactly 0
select is(
  (select coalesce(sum(net_minor), 0)::bigint from public.compute_group_nets('ffffffff-0000-0000-0000-00000000000b')),
  0::bigint,
  'Vector 11: sum of all nets is exactly 0 (BC1)'
);

-- Test 3: compute_simplified_debts matches expected payments
select results_eq(
  $$ select seq, from_user, to_user, amount_minor from public.compute_simplified_debts('ffffffff-0000-0000-0000-00000000000b') order by seq $$,
  $$ values
    (1::int, 'cccccccc-3333-0000-0000-000000000003'::uuid, 'aaaaaaaa-1111-0000-0000-000000000001'::uuid, 30000::bigint),
    (2::int, 'dddddddd-4444-0000-0000-000000000004'::uuid, 'aaaaaaaa-1111-0000-0000-000000000001'::uuid, 10000::bigint) $$,
  'Vector 11: compute_simplified_debts returns exact expected suggested payments'
);

-- Test 4: Invariant BS2: applying all suggested payments brings every balance to exactly 0
with applied as (
  select n.member_id,
         (n.net_minor + coalesce(se.amt, 0) - coalesce(re.amt, 0))::bigint as final_net
    from public.compute_group_nets('ffffffff-0000-0000-0000-00000000000b') n
    left join (select from_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-00000000000b') group by from_user) se on se.from_user = n.member_id
    left join (select to_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-00000000000b') group by to_user) re on re.to_user = n.member_id
)
select is(
  (select count(*)::int from applied where final_net <> 0),
  0,
  'Vector 11: applying suggested payments brings every balance to 0 (BS2)'
);

-- Test 5: Invariant BS1: at most n - 1 payments for n people with non-zero balances
select ok(
  (select count(*)::int from public.compute_simplified_debts('ffffffff-0000-0000-0000-00000000000b')) <= 2,
  'Vector 11: suggested payments count <= 2 (BS1)'
);

-- =============================================================================
-- Vector 12: Vector 1, then the deleted expense is restored
-- =============================================================================
insert into public.groups (id, name, currency, created_by)
values ('ffffffff-0000-0000-0000-00000000000c', 'Vector 12 Group', 'INR', 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.group_members (group_id, user_id, role, status)
values
  ('ffffffff-0000-0000-0000-00000000000c', 'aaaaaaaa-1111-0000-0000-000000000001', 'member', 'active'),
  ('ffffffff-0000-0000-0000-00000000000c', 'bbbbbbbb-2222-0000-0000-000000000002', 'member', 'active'),
  ('ffffffff-0000-0000-0000-00000000000c', 'cccccccc-3333-0000-0000-000000000003', 'member', 'active');

insert into public.expenses (id, group_id, amount_minor, paid_by, split_type, expense_date, created_by)
values ('e0000000-0000-0000-0000-000000000015', 'ffffffff-0000-0000-0000-00000000000c', 30000, 'aaaaaaaa-1111-0000-0000-000000000001', 'equal', current_date, 'aaaaaaaa-1111-0000-0000-000000000001');

insert into public.expense_splits (expense_id, user_id, share_minor)
values
  ('e0000000-0000-0000-0000-000000000015', 'aaaaaaaa-1111-0000-0000-000000000001', 10000),
  ('e0000000-0000-0000-0000-000000000015', 'bbbbbbbb-2222-0000-0000-000000000002', 10000),
  ('e0000000-0000-0000-0000-000000000015', 'cccccccc-3333-0000-0000-000000000003', 10000);

-- Soft delete and restore expense to test restoration behavior
update public.expenses set deleted_at = now(), deleted_by = 'aaaaaaaa-1111-0000-0000-000000000001' where id = 'e0000000-0000-0000-0000-000000000015';
update public.expenses set deleted_at = null, deleted_by = null where id = 'e0000000-0000-0000-0000-000000000015';

-- Test 1: compute_group_nets matches expected nets
select results_eq(
  $$ select member_id, net_minor from public.compute_group_nets('ffffffff-0000-0000-0000-00000000000c') order by net_minor desc, member_id asc $$,
  $$ values
    ('aaaaaaaa-1111-0000-0000-000000000001'::uuid, 20000::bigint),
    ('bbbbbbbb-2222-0000-0000-000000000002'::uuid, -10000::bigint),
    ('cccccccc-3333-0000-0000-000000000003'::uuid, -10000::bigint) $$,
  'Vector 12: compute_group_nets returns exact expected nets'
);

-- Test 2: Invariant BC1: sum of all nets must be exactly 0
select is(
  (select coalesce(sum(net_minor), 0)::bigint from public.compute_group_nets('ffffffff-0000-0000-0000-00000000000c')),
  0::bigint,
  'Vector 12: sum of all nets is exactly 0 (BC1)'
);

-- Test 3: compute_simplified_debts matches expected payments
select results_eq(
  $$ select seq, from_user, to_user, amount_minor from public.compute_simplified_debts('ffffffff-0000-0000-0000-00000000000c') order by seq $$,
  $$ values
    (1::int, 'bbbbbbbb-2222-0000-0000-000000000002'::uuid, 'aaaaaaaa-1111-0000-0000-000000000001'::uuid, 10000::bigint),
    (2::int, 'cccccccc-3333-0000-0000-000000000003'::uuid, 'aaaaaaaa-1111-0000-0000-000000000001'::uuid, 10000::bigint) $$,
  'Vector 12: compute_simplified_debts returns exact expected suggested payments'
);

-- Test 4: Invariant BS2: applying all suggested payments brings every balance to exactly 0
with applied as (
  select n.member_id,
         (n.net_minor + coalesce(se.amt, 0) - coalesce(re.amt, 0))::bigint as final_net
    from public.compute_group_nets('ffffffff-0000-0000-0000-00000000000c') n
    left join (select from_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-00000000000c') group by from_user) se on se.from_user = n.member_id
    left join (select to_user, sum(amount_minor) as amt from public.compute_simplified_debts('ffffffff-0000-0000-0000-00000000000c') group by to_user) re on re.to_user = n.member_id
)
select is(
  (select count(*)::int from applied where final_net <> 0),
  0,
  'Vector 12: applying suggested payments brings every balance to 0 (BS2)'
);

-- Test 5: Invariant BS1: at most n - 1 payments for n people with non-zero balances
select ok(
  (select count(*)::int from public.compute_simplified_debts('ffffffff-0000-0000-0000-00000000000c')) <= 2,
  'Vector 12: suggested payments count <= 2 (BS1)'
);

rollback;
