import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const fixturePath = path.resolve(__dirname, '../tests/fixtures/split-vectors.json');
const rawData = fs.readFileSync(fixturePath, 'utf8');
const fixture: SplitVectorsFixture = JSON.parse(rawData);

let testCount = 0;
for (const v of fixture.vectors) {
  if (v.expectedShares) {
    testCount += 2; // results_eq + sum check
  } else if (v.expectedError) {
    testCount += 1; // throws_ok
  }
}

let sql = `-- Auto-generated by scripts/gen-split-tests.ts from tests/fixtures/split-vectors.json
-- Do not edit manually. Run 'node --experimental-strip-types scripts/gen-split-tests.ts' to regenerate.

begin;
select plan(${testCount});

set local role postgres;

`;

for (const v of fixture.vectors) {
  const participantsJson = JSON.stringify(v.participants);
  if (v.expectedShares) {
    const valuesRows = v.expectedShares
      .map(
        (s) =>
          `    ('${s.user_id}'::uuid, ${s.share_minor}::bigint, ${
            s.percent_bp === null ? 'null::integer' : `${s.percent_bp}::integer`
          })`
      )
      .join(',\n');

    sql += `-- Vector ${v.id}: ${v.type} split for amount ${v.amountMinor}
select results_eq(
  $$ select user_id, share_minor, percent_bp from public.compute_shares('${v.type}', ${v.amountMinor}::bigint, '${participantsJson}'::jsonb) order by user_id $$,
  $$ values
${valuesRows} $$,
  'Vector ${v.id}: compute_shares (${v.type}, amount ${v.amountMinor}) returns exact expected shares'
);

select is(
  (select sum(share_minor)::bigint from public.compute_shares('${v.type}', ${v.amountMinor}::bigint, '${participantsJson}'::jsonb)),
  ${v.amountMinor}::bigint,
  'Vector ${v.id}: sum of shares equals total amount (${v.amountMinor})'
);

`;
  } else if (v.expectedError) {
    sql += `-- Vector ${v.id}: ${v.type} error test expecting '${v.expectedError}'
select throws_ok(
  $$ select * from public.compute_shares('${v.type}', ${v.amountMinor}::bigint, '${participantsJson}'::jsonb) $$,
  'P0001',
  '${v.expectedError}',
  'Vector ${v.id}: ${v.type} throws expected error ${v.expectedError}'
);

`;
  }
}

sql += `rollback;
`;

// Write to supabase/tests/split_vectors.sql as requested by prompt
const targetFile1 = path.resolve(__dirname, '../supabase/tests/split_vectors.sql');
fs.writeFileSync(targetFile1, sql, 'utf8');
console.log(`Generated ${targetFile1} with ${testCount} tests.`);

// Remove redundant file in database/ if present so tests do not run twice
const targetFile2 = path.resolve(__dirname, '../supabase/tests/database/split_vectors.test.sql');
if (fs.existsSync(targetFile2)) {
  fs.unlinkSync(targetFile2);
}
