import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface NetItem {
  member_id: string;
  net_minor: number;
}

interface PaymentItem {
  seq: number;
  from_user: string;
  to_user: string;
  amount_minor: number;
}

interface SplitItem {
  user_id: string;
  share_minor: number;
  percent_bp?: number;
}

interface ExpenseItem {
  id: string;
  paid_by: string;
  amount_minor: number;
  split_type: string;
  splits: SplitItem[];
  deleted?: boolean;
  restored?: boolean;
}

interface SettlementItem {
  id: string;
  from_user: string;
  to_user: string;
  amount_minor: number;
  status: string;
  created_by: string;
}

interface BalanceVector {
  id: number;
  scenario: string;
  members: string[];
  expenses: ExpenseItem[];
  settlements: SettlementItem[];
  expectedNets: NetItem[];
  expectedPayments: PaymentItem[];
}

interface BalanceVectorsFixture {
  version: string;
  description: string;
  constants: {
    users: Record<string, string>;
  };
  vectors: BalanceVector[];
}

const fixturePath = path.resolve(__dirname, '../tests/fixtures/balance-vectors.json');
const rawData = fs.readFileSync(fixturePath, 'utf8');
const fixture: BalanceVectorsFixture = JSON.parse(rawData);

// 5 tests per vector (nets, sum=0, payments, applied=0, count<=n-1)
const testCount = fixture.vectors.length * 5;

let sql = `-- Auto-generated by scripts/gen-balance-tests.ts from tests/fixtures/balance-vectors.json
-- Do not edit manually. Run 'node --experimental-strip-types scripts/gen-balance-tests.ts' to regenerate.

begin;
select plan(${testCount});

set local role postgres;

-- Insert shared test users
insert into auth.users (id, email)
values
  ('${fixture.constants.users.a}', 'veca@example.com'),
  ('${fixture.constants.users.b}', 'vecb@example.com'),
  ('${fixture.constants.users.c}', 'vecc@example.com'),
  ('${fixture.constants.users.d}', 'vecd@example.com')
on conflict (id) do nothing;

`;

for (const v of fixture.vectors) {
  const groupId = `ffffffff-0000-0000-0000-${v.id.toString(16).padStart(12, '0')}`;
  const nonZeroMembers = v.expectedNets.filter((n) => n.net_minor !== 0).length;
  const maxPayments = Math.max(0, nonZeroMembers - 1);

  sql += `-- =============================================================================
-- Vector ${v.id}: ${v.scenario}
-- =============================================================================
insert into public.groups (id, name, currency, created_by)
values ('${groupId}', 'Vector ${v.id} Group', 'INR', '${v.members[0]}');

insert into public.group_members (group_id, user_id, role, status)
values
${v.members.map((m) => `  ('${groupId}', '${m}', 'member', 'active')`).join(',\n')};

`;

  // Insert expenses and splits
  for (const exp of v.expenses) {
    const isDeleted = exp.deleted === true;
    sql += `insert into public.expenses (id, group_id, amount_minor, paid_by, split_type, expense_date, created_by${
      isDeleted ? ', deleted_at, deleted_by' : ''
    })
values ('${exp.id}', '${groupId}', ${exp.amount_minor}, '${exp.paid_by}', '${exp.split_type}', current_date, '${
      exp.paid_by
    }'${isDeleted ? `, now(), '${exp.paid_by}'` : ''});

insert into public.expense_splits (expense_id, user_id, share_minor)
values
${exp.splits.map((s) => `  ('${exp.id}', '${s.user_id}', ${s.share_minor})`).join(',\n')};

`;
    if (exp.restored) {
      sql += `-- Soft delete and restore expense to test restoration behavior
update public.expenses set deleted_at = now(), deleted_by = '${exp.paid_by}' where id = '${exp.id}';
update public.expenses set deleted_at = null, deleted_by = null where id = '${exp.id}';

`;
    }
  }

  // Insert settlements
  for (const st of v.settlements) {
    const isConfirmed = st.status === 'confirmed';
    sql += `insert into public.settlements (id, group_id, from_user, to_user, amount_minor, method, status, created_by${
      isConfirmed ? ', confirmed_at' : ''
    })
values ('${st.id}', '${groupId}', '${st.from_user}', '${st.to_user}', ${st.amount_minor}, 'cash', '${st.status}', '${
      st.created_by
    }'${isConfirmed ? ', now()' : ''});

`;
  }

  // Expected nets rows
  const netRows = v.expectedNets
    .map((n) => `    ('${n.member_id}'::uuid, ${n.net_minor}::bigint)`)
    .join(',\n');

  // Expected payments rows
  const paymentRows =
    v.expectedPayments.length > 0
      ? v.expectedPayments
          .map(
            (p) =>
              `    (${p.seq}::int, '${p.from_user}'::uuid, '${p.to_user}'::uuid, ${p.amount_minor}::bigint)`
          )
          .join(',\n')
      : null;

  sql += `-- Test 1: compute_group_nets matches expected nets
select results_eq(
  $$ select member_id, net_minor from public.compute_group_nets('${groupId}') order by net_minor desc, member_id asc $$,
  $$ values
${netRows} $$,
  'Vector ${v.id}: compute_group_nets returns exact expected nets'
);

-- Test 2: Invariant BC1: sum of all nets must be exactly 0
select is(
  (select coalesce(sum(net_minor), 0)::bigint from public.compute_group_nets('${groupId}')),
  0::bigint,
  'Vector ${v.id}: sum of all nets is exactly 0 (BC1)'
);

-- Test 3: compute_simplified_debts matches expected payments
`;

  if (paymentRows) {
    sql += `select results_eq(
  $$ select seq, from_user, to_user, amount_minor from public.compute_simplified_debts('${groupId}') order by seq $$,
  $$ values
${paymentRows} $$,
  'Vector ${v.id}: compute_simplified_debts returns exact expected suggested payments'
);
`;
  } else {
    sql += `select is_empty(
  $$ select seq, from_user, to_user, amount_minor from public.compute_simplified_debts('${groupId}') $$,
  'Vector ${v.id}: compute_simplified_debts returns empty when all settled'
);
`;
  }

  sql += `
-- Test 4: Invariant BS2: applying all suggested payments brings every balance to exactly 0
with applied as (
  select n.member_id,
         (n.net_minor + coalesce(se.amt, 0) - coalesce(re.amt, 0))::bigint as final_net
    from public.compute_group_nets('${groupId}') n
    left join (select from_user, sum(amount_minor) as amt from public.compute_simplified_debts('${groupId}') group by from_user) se on se.from_user = n.member_id
    left join (select to_user, sum(amount_minor) as amt from public.compute_simplified_debts('${groupId}') group by to_user) re on re.to_user = n.member_id
)
select is(
  (select count(*)::int from applied where final_net <> 0),
  0,
  'Vector ${v.id}: applying suggested payments brings every balance to 0 (BS2)'
);

-- Test 5: Invariant BS1: at most n - 1 payments for n people with non-zero balances
select ok(
  (select count(*)::int from public.compute_simplified_debts('${groupId}')) <= ${maxPayments},
  'Vector ${v.id}: suggested payments count <= ${maxPayments} (BS1)'
);

`;
}

sql += `rollback;
`;

const targetFile = path.resolve(__dirname, '../supabase/tests/balance_vectors.sql');
fs.writeFileSync(targetFile, sql, 'utf8');
console.log(`Generated ${targetFile} with ${testCount} tests.`);
